### PR TITLE
Optional behavior for Deal creation

### PR DESCRIPTION
**Pull request by AlpBilgin**
- Allows a note message preamble to be set in component configuration
- Allows the default owner_id to be overwritten in component configuration
- Looks for person_id and org_id values in incoming message. If they are not defined, creates sub entities and assigns their returned ids into missing message fields. 
- Looks for two components to compose a note message. One is supplied in component configuration (see above: first item) and one is supplied in individual messages. Found strings are concatenated.
- Creates a follow-up activity whose subject is the deal title. It is assigned to the highest priority user ID available. (If none are available PD API will assign it to API key owner.) A date or time is not set.
- Testing is extended to cover new data fields

### CODE REVIEW

**Comment by AlpBilgin** [comment]
Partially solves #4

**Comment by zubairov** [comment]
Nice one. It's definitely going into right direction, but tbh I expected 3 (or more) actions instead of one complicated action with more logic inside. Why wouldn't we use e.io integrator's creativity to 'design' the logic instead of hardcoding it into the one single action?

Can you split this one large action into three, e.g.
- [ ] Create Person and Organization
- [ ] Attach a Note
- [ ] Create a Deal

**Comment by AlpBilgin** [comment]
Hello @zubairov,

I have created an action for each object type. They look for a particular id number in the incoming message, if they can't find the id they need, they create an object and append the returned id to the message.

The implementation feels a bit naive. Do you have any recommended patterns for such structures?

**Comment by AlpBilgin** [comment]
Hello @zubairov ,

I attempted to implement your explanations and the advice. Could you please check the latest state of the code?

**Pull request merged**
